exports.COMMON = {
    ERROR: {
        NEW_PASSWORD_REQUIRED: "new password required",
        UNEXPECTED_ERROR: "An unexpected error occurred",
        UNKNOWN_ERROR: "UnknownError",
        INVALID_PASSWORD: "Password does not meet the requirements",
        INVALID_PARAMETER: "Invalid parameter provided",
        SESSION_EXPIRED: "Session has expired. Please try signing in again.",
        BAD_CREDENTIALS: "Bad credentials",
        USER_NOTE_CONFIRMED: "User is not confirmed",
        PASSWORD_RESET_REQUIRED: "Password reset required",
        FAILED_TO_SEND_NOTIFICATION: "Failed to send notifications for expired task",
        FAILED_TO_SUBSCRIBE_CLOSED_TASKS_NOTIFICATION: "Failed to subscribe to closed task notifications",
        FAILED_TO_SUBSCRIBE_TASK_DEADLINE_NOTIFICATION: "Failed to subscribe to task deadline notifications",
    },
    SUCCESS_MSG: {
        SUBSCRIBED_CLOSED_NOTIFICATION: "Successfully subscribed to closed task notifications",
        SUBSCRIBED_TASK_DEADLINE_NOTIFICATION: "Successfully subscribed to task deadline notifications",
        PASSWORD_RESET_SUCCESS: "Password reset successfully",
    },
    EXCEPTIONS: {
        INVALID_PARAMETER: "InvalidParameterException",
        INVALID_PAASWORD: "InvalidPasswordException",
        EXPIRED_CODE: "ExpiredCodeException",
        NOT_AUTHORIZED: "NotAuthorizedException",
        USER_NOT_FOUND: "UserNotFoundException",
        USER_NOT_CONFIRMED: "UserNotConfirmedException",
        PASSWORD_RESET_REQUIRED: "PasswordResetRequiredException",
    },
    HEADERS: {
        ACCESS_CONTROL_ALLOW_ORIGIN: "*",
        CONTENT_TYPE: "application/json",
    },
    STATUS_CODES: {
        OK: 200,
        CREATED: 201,
        NO_CONTENT: 204,
        BAD_REQUEST: 400,
        UNAUTHORIZED: 401,
        FORBIDDEN: 403,
        NOT_FOUND: 404,
        CONFLICT: 409,
        INTERNAL_SERVER_ERROR: 500,
        SERVICE_UNAVAILABLE: 503,
    },
};
